osx_image: xcode8.1
language: objective-c
branches:
 only:
  - develop
  - master
notifications:
 email: false
before_install:
 - gem install bundler
 - bundle install && brew bundle
script:
 - bundle exec fastlane tests
